AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
# @see https://github.com/rubocop/rubocop/blob/9f24166d04922361a84d2e1e95ef4d15f81443e0/config/default.yml#L63
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/Documentation:
  Enabled: false