AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
    - yarn.lock
    - vendor/**/*.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/Documentation:
  Enabled: false