AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - db/schema.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/Documentation:
  Enabled: false