name: "CI"
on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: some-password
          POSTGRES_USER: test-app-user
          POSTGRES_DB: todo-app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
      - name: Tests
        run: bin/rails test
        env:
          POSTGRES_PASSWORD: some-password
          POSTGRES_USER: test-app-user
          POSTGRES_DB: todo-app
          POSTGRES_HOST: localhost
